# Generated by Django 4.1.5 on 2023-01-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="cover_img",
            field=models.ImageField(
                blank=True,
                default="static/images/20221212_122250_1_1_1.jpg",
                null=True,
                upload_to="",
            ),
        ),
    ]
