# Generated by Django 4.1.5 on 2023-01-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_cover_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="cover_img",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
